routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthorController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BookController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard')->middleware('auth');

Route::resource('authors', AuthorController::class)->middleware('auth');
Route::resource('books', BookController::class)->only(['create', 'store', 'destroy']);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class AuthorController extends Controller
{
    public function index()

    {

    
        $response = Http::withToken(session('access_token'))->withOptions(['verify' => false])
                        ->get('https://candidate-testing.api.royal-apps.io/api/v2/authors');

        $authors = $response->json()['items'];
        return view('authors.index', compact('authors'));
    }

    public function show($id)
    {
        $authorResponse = Http::withToken(session('access_token'))->withOptions(['verify' => false])
                              ->get("https://candidate-testing.api.royal-apps.io/api/v2/authors/{$id}");
        $author = $authorResponse->json();
        
        return view('authors.show', compact('author'));
    }

   public function destroy($id)
{
    // Ensure the author has no related books
    $booksResponse = Http::withToken(session('access_token'))->withOptions(['verify' => false])
    ->get("https://candidate-testing.api.royal-apps.io/api/v2/authors/{$id}");
    $books = $booksResponse->json()['books'];
    if (count($books) > 0) {
        return redirect()->back()->with('error', 'Author cannot be deleted because there are related books.');
    }

    // Proceed to delete the author if there are no books
    $response = Http::withToken(session('access_token'))->withOptions(['verify' => false])
                    ->delete("https://candidate-testing.api.royal-apps.io/api/v2/authors/{$id}");

    if ($response->successful()) {
        return redirect()->route('authors.index')->with('success', 'Author deleted successfully.');
    } else {
        return redirect()->back()->with('error', 'Failed to delete the author.');
    }
}
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use DateTime;


class BookController extends Controller
{
    public function create()
    {
        $response = Http::withToken(session('access_token'))->withOptions(['verify' => false])
                        ->get('https://candidate-testing.api.royal-apps.io/api/v2/authors');
    
        $authors = $response->json()['items'];
        return view('books.create', compact('authors'));
    }
    
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'author_id' => 'required|integer',
            'description' => 'required|string',
            'isbn' => 'required|string',
            'release_date' => 'required|date',
            'format' => 'required|string',
            'number_of_pages' => 'required|integer',
        ]); 

        $releaseDate = new DateTime($request->release_date);
        $formattedReleaseDate = $releaseDate->format('Y-m-d\TH:i:s.v\Z');
        $response = Http::withToken(session('access_token'))->withOptions(['verify' => false])
        ->post('https://candidate-testing.api.royal-apps.io/api/v2/books', [
            'author' => ['id' => $request->author_id],
            'title' => $request->title,
            'description' => $request->description,
            'isbn' => $request->isbn,
            'format' => $request->format,
            'number_of_pages' => (int)$request->number_of_pages,
            'release_date' => (string)$formattedReleaseDate,

        ]);

        if ($response->successful()) {
        return redirect()->route('authors.show', $request->author_id)->with('success', 'Book added successfully');
        } else {
        return back()->withErrors(['message' => 'Failed to add book']);
        }
    }
    
    public function destroy($id)
{
    $response = Http::withToken(session('access_token'))->withOptions(['verify' => false])
                    ->delete("https://candidate-testing.api.royal-apps.io/api/v2/books/{$id}");

    if ($response->successful()) {
        return back()->with('success', 'Book deleted successfully.');
    } else {
        return back()->with('error', 'Failed to delete the book. Please try again.');
    }
}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/authors/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        h1 {
            background-color: #4CAF50;
            color: white;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        a.add-book {
            display: inline-block;
            margin: 20px 0;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }
        a.add-book:hover {
            background-color: #45a049;
        }
        .alert {
            padding: 15px;
            margin: 20px 0;
            border: 1px solid transparent;
            border-radius: 4px;
            width: 100%;
            box-sizing: border-box;
        }
        .alert-success {
            color: #155724;
            background-color: #d4edda;
            border-color: #c3e6cb;
        }
        .alert-error {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .error-list {
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
            padding: 15px;
            border-radius: 5px;
            width: 100%;
            box-sizing: border-box;
        }
        table {
            width: 100%;
            margin: 20px 0;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 15px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        a.view {
            color: #1E90FF;
            padding: 5px 10px;
            border: 1px solid #1E90FF;
            border-radius: 5px;
            background-color: #f1f1f1;
            text-decoration: none;
            transition: background-color 0.3s ease, color 0.3s ease;
        }
        a.view:hover {
            background-color: #1E90FF;
            color: white;
        }
        button.delete {
            color: #FF6347;
            padding: 5px 10px;
            border: 1px solid #FF6347;
            border-radius: 5px;
            background-color: #f1f1f1;
            cursor: pointer;
            transition: background-color 0.3s ease, color 0.3s ease;
        }
        button.delete:hover {
            background-color: #FF6347;
            color: white;
        }
        form {
            display: inline;
        }
    </style>
</head>
<body>
    <h1>Authors</h1>
    <div class="container">
        <a href="{{ route('books.create') }}" class="add-book">Add Book</a>
        @if (session('success'))
            <div class="alert alert-success">{{ session('success') }}</div>
        @endif
        @if (session('error'))
            <div class="alert alert-error">{{ session('error') }}</div>
        @endif
        @if ($errors->any())
            <div class="error-list">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($authors as $author)
                    <tr>
                        <td>{{ $author['first_name'] }} {{ $author['last_name'] }}</td>
                        <td>
                            <a href="{{ route('authors.show', $author['id']) }}" class="view">View</a>
                            <form action="{{ route('authors.destroy', $author['id']) }}" method="POST" style="display:inline;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="delete">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
</html>

resources/views/authors/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Author Details</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .author-details {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
            margin-bottom: 30px;
        }
        .author-details h2 {
            margin-bottom: 20px;
            color: #007bff;
        }
        .author-details p {
            margin: 10px 0;
        }
        .book-list {
            list-style-type: none;
            padding: 0;
        }
        .book-list li {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            padding: 20px;
            position: relative;
        }
        .book-title {
            font-size: 1.2em;
            margin-bottom: 10px;
            color: #333;
            display: flex;
            align-items: center;
        }
        .book-title i {
            margin-right: 10px;
            color: #007bff;
        }
        .book-details p {
            margin: 5px 0;
        }
        .delete-button {
            position: absolute;
            top: 10px;
            right: 10px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 3px;
            transition: background-color 0.3s ease;
        }
        .delete-button:hover {
            background-color: #c82333;
        }
        .alert {
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .alert-success {
            background-color: #d4edda;
            color: #155724;
        }
        .alert-error {
            background-color: #f8d7da;
            color: #721c24;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="header">
            <h1>{{ $author['first_name'] }} {{ $author['last_name'] }}</h1>
            <i class="fas fa-user"></i>
        </div>
        <div class="author-details">
            <h2>Author Information</h2>
            <p><strong>Birthday:</strong> {{ \Carbon\Carbon::parse($author['birthday'])->format('F d, Y') }}</p>
            <p><strong>Place of Birth:</strong> {{ $author['place_of_birth'] }}</p>
            <p><strong>Gender:</strong> {{ ucfirst($author['gender']) }}</p>
            <p><strong>Biography:</strong> {{ $author['biography'] }}</p>
        </div>

        @if(session('success'))
            <div class="alert alert-success" id="success-alert">
                {{ session('success') }}
            </div>
        @endif

        @if(session('error'))
            <div class="alert alert-error" id="error-alert">
                {{ session('error') }}
            </div>
        @endif

        <h2>Books</h2>
        <ul class="book-list">
            @foreach ($author['books'] as $book)
                <li>
                    <div class="book-title">
                        <i class="fas fa-book"></i>
                        {{ $book['title'] }}
                    </div>
                    <div class="book-details">
            <p><strong>Description:</strong> {{ $book['description'] }}</p>
            <p><strong>ISBN:</strong> {{ $book['isbn'] }}</p>
            <p><strong>Format:</strong> {{ $book['format'] }}</p>
            <p><strong>Number of Pages:</strong> {{ $book['number_of_pages'] }}</p>
            @if (!empty($book['release_date']))
                <p><strong>Release Date:</strong> {{ \Carbon\Carbon::parse($book['release_date'])->format('F d, Y') }}</p>
            @endif
        </div>
                    <form action="{{ route('books.destroy', $book['id']) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="delete-button">Delete</button>
                    </form>
                </li>
            @endforeach
        </ul>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            setTimeout(function () {
                let successAlert = document.getElementById('success-alert');
                if (successAlert) {
                    successAlert.style.display = 'none';
                }
                let errorAlert = document.getElementById('error-alert');
                if (errorAlert) {
                    errorAlert.style.display = 'none';
                }
            }, 5000);
        });
    </script>
</body>
</html>

resources/views/books/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
            margin-top: 30px;
        }
        form {
            width: 80%;
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        input[type="text"],
        select,
        textarea,
        input[type="datetime-local"],
        input[type="number"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        select {
            appearance: none;
            -webkit-appearance: none;
            -moz-appearance: none;
            background-image: url('data:image/svg+xml;utf8,<svg fill="#666" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M7.406 9.594l4 4c.39.39 1.024.39 1.414 0l4-4c.39-.39.39-1.023 0-1.414-.39-.39-1.023-.39-1.414 0L12 11.586 8.82 8.406c-.39-.39-1.023-.39-1.414 0-.39.39-.39 1.023 0 1.414z"/></svg>');
            background-size: 12px;
            background-repeat: no-repeat;
            background-position: right 10px top 50%;
            padding-right: 30px;
        }
        textarea {
            resize: vertical;
        }
        button[type="submit"] {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 15px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            width: 100%;
            display: block;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        .error-msg {
            color: red;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <h1>Add Book</h1>
    <form method="POST" action="{{ route('books.store') }}">
        @csrf
        <input type="text" name="title" placeholder="Book Title" required>
        <select name="author_id" required>
            <option value="" disabled selected>Select Author</option>
            @foreach ($authors as $author)
                <option value="{{ $author['id'] }}">{{ $author['first_name'] }} {{ $author['last_name'] }}</option>
            @endforeach
        </select>
        <input type="datetime-local" id="release_date" name="release_date" placeholder="Release Date" required>
        <textarea name="description" placeholder="Description" required></textarea>
        <input type="text" name="isbn" placeholder="ISBN" required>
        <input type="text" name="format" placeholder="Format" required>
        <input type="number" name="number_of_pages" placeholder="Number of Pages" required>
        <button type="submit">Add Book</button>
    </form>
</body>
</html>

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F4F4F4;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            width: 80%;
            max-width: 600px;
            text-align: center;
            background-color: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 2.5em;
            margin-bottom: 20px;
            color: #4CAF50;
        }
        nav {
            margin-bottom: 30px;
        }
        nav a {
            text-decoration: none;
            color: #007BFF;
            margin: 0 15px;
            font-size: 1.2em;
            transition: color 0.3s ease;
        }
        nav a:hover {
            color: #0056B3;
        }
        form {
            display: inline-block;
            margin-top: 20px;
        }
        .logout-button {
            background-color: #DC3545;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 1em;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .logout-button:hover {
            background-color: #C82333;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome, {{ session('user_name') }}</h1>
        <nav>
            <a href="{{ route('authors.index') }}">View Authors</a>
            <a href="{{ route('books.create') }}">Add Book</a>
        </nav>
        <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit" class="logout-button">Logout</button>
        </form>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidate Testing App</title>
</head>
<body>
    @if(session('access_token'))
        <p>Welcome, {{ session('user_name') }}</p>
        <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit">Logout</button>
        </form>
    @endif
    @yield('content')
</body>
</html>

resources/views/layouts/header.blade.php
<header>
    <style>
     /* styles.css */

header {
    background-color: #333;
    color: #fff;
    padding: 10px 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.logo {
    font-size: 24px;
    font-weight: bold;
}

.user-dropdown {
    position: relative;
}

.user-icon {
    cursor: pointer;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 120px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    z-index: 1;
    right: 0;
}

.dropdown-content a {
    color: #333;
    padding: 10px;
    display: block;
    text-decoration: none;
}

.dropdown-content a:hover {
    background-color: #ddd;
}

.username {
    font-weight: bold;
    padding: 5px;
    border-bottom: 1px solid #ddd;
}

    </style>
    <div class="logo">ROYAL APP</div>
    <div class="user-dropdown">
        <div class="user-icon"><i class="fas fa-user"></i></div>
        <div class="dropdown-content">
            <span class="username">{{ session('user_name') }}</span>
            <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit" class="logout-button">Logout</button>
        </form>
        </div>
    </div>
</header>   